# Generated by Django 5.0.1 on 2024-03-14 08:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
