# Generated by Django 5.0.1 on 2024-03-14 09:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50)),
                ('about_des', tinymce.models.HTMLField()),
                ('aboutDoc_name', models.CharField(max_length=50)),
                ('aboutDoc_specialization', models.CharField(max_length=50)),
            ],
        ),
    ]
