# Generated by Django 5.0.1 on 2024-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutDoc_name', models.CharField(max_length=50)),
                ('aboutDoc_specialization', models.CharField(max_length=50)),
            ],
        ),
    ]
