# Generated by Django 5.0.1 on 2024-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='aboutDoc_image',
            field=models.FileField(default=None, null=True, unique=True, upload_to='doctors/'),
        ),
    ]
