# Generated by Django 5.0.1 on 2024-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freeTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_free', models.CharField(max_length=50)),
                ('phone_free', models.CharField(max_length=50)),
                ('treatment_free', models.CharField(max_length=50)),
            ],
        ),
    ]
